### PR TITLE
Jwt token general

### PR DESCRIPTION
**Pull request by AyalaSprei**

### CODE REVIEW

**Review by moriyahazan — CHANGES_REQUESTED** [review]
your code cant cmpile 
please fix and I will review

**Comment by moriyahazan** [comment]
X is related to compilation

בתאריך יום ג׳, 25 ביולי 2023, 21:52, מאת AyalaSprei ‏<
***@***.***>:

**Comment by AyalaSprei** [comment]
K, got it.
Just one file that somehow wasn't pushed

**Comment by AyalaSprei** [comment]
No, sorry. 
I see it's still with X
What do you advise me to do?
I have no idea

**Comment by moriyahazan** [comment]
merge now again from main
i solved the issue

**Comment by AyalaSprei** [comment]
I merged
Do you have any idea what's the problem now?

**Comment by AyalaSprei** [comment]
It must be problems in the pushing ot whatever in git hub, because it runs
זה כבר מחרפן
In addition, I noticed there is changes in application properties. I remember I wrote there:
spring.data.mongodb.uri=mongodb://localhost:27017/Orders
spring.data.mongodb.database=Orders
spring.data.mongodb.auto-index-creation=true 

What did happen to this code?
I thoght maybe you changed it when adding the tests, while since, the communicate to DB passed to a new DB that was created in the name 'test'.

**Comment by moriyahazan** [comment]
According to git history, Ayala B removed the mongodb properties probably my mistake
Please ask her to fix it

Your compilation error caused due to unittest, after you added tocken you need to align the unittest
Did you see my Zoom on unit testing? please try to understand which change you need to do in order to support token mechanism 

Write me if you still cant solve the issue I will take your branch and fix it today later.

**Pull request merged**
