### PR TITLE
Communicate to rabbitmq

### PR DESCRIPTION
**Pull request by MaayanShore**
Everything works but I couldn't send localDate I need your help. thank you very much!

### CODE REVIEW

**Comment by moriyahazan** [comment]
Please ask Shirel 
I helped her to solve the issue with local data

**Comment by moriyahazan** [comment]
and please fix the compilation error you have

**Comment by moriyahazan** [comment]
> Everything works but I couldn't send localDate I need your help. thank you very much!

Did you solve the issue of localdate?

**Comment by MaayanShore** [comment]
no

‫בתאריך יום ב׳, 21 באוג׳ 2023 ב-23:16 מאת ‪Moriya‬‏ <‪
***@***.***‬‏>:‬

**Pull request merged**
