### PR TITLE
status of orders graf

### PR DESCRIPTION
**Pull request by s0583224249**
orders that cancelled or deleivered  in few last month.

### CODE REVIEW

**Review by moriyahazan — CHANGES_REQUESTED** [review]
One comment
please fix and I will approve

**Comment by moriyahazan** [comment]
Why this PR still open??

**Comment by moriyahazan** [comment]
This PR is still open

**Comment by s0583224249** [comment]
I changed the 0/1 to delivered/cancelled but I didn't succeed to do it for few types of cancelled.
to compare "equalToValue" to more then value.

**Comment by moriyahazan** [comment]
> I changed the 0/1 to delivered/cancelled but I didn't succeed to do it for few types of cancelled. to compare "equalToValue" to more then value.

why you didt use enum of order status?

**Comment by moriyahazan** [comment]
> should I use the enum of status that is in the model? there is not all types of cancelled status there.

sure, you should use same enum

**Comment by s0583224249** [comment]
thank you

**Comment by moriyahazan** [comment]
Did you merge the code?

בתאריך יום ב׳, 28 באוג׳ 2023, 11:34, מאת s0583224249 ‏<
***@***.***>:

**Pull request closed without merging**
